"The following file contains: Plotting functions for the different sections in dircol.ipynb
Ref_IPOPT_3D_Plot()- Plot reference vs IPOPT orbit (3D)
Ref_IPOPT_XYZ_Plot()- Plot reference vs IPOPT orbit (XYZ Individually)
IPOPT_Timesteps_Plot()-Plot the variable timesteps
Family_Orbits_Plot()-Plot family of orbits generated by IPOPT
TVQLR_Plot()-TVLQR Plotting"

# Plot reference vs IPOPT orbit (3D)
function Ref_IPOPT_3D_Plot()
    mat"""
    title('Reference vs IPOPT Result', 'FontSize', 20)
    hold on
    grid on
    plot3($xonly, $yonly, $zonly, 'DisplayName','IPOPT Results', 'LineWidth', 2)
    plot3($xRef, $yRef, $zRef, 'DisplayName','Reference', 'LineWidth', 2)
    xlabel('X', 'FontSize', 16)
    ylabel('Y', 'FontSize', 16)
    zlabel('Z', 'FontSize', 16)
    view(25, 15)
    hold off
    ax = gca;
    ax.FontSize = 14;
    legend('FontSize', 16)
    """    
end

# Plot reference vs IPOPT orbit (XYZ Individually)
function Ref_IPOPT_XYZ_Plot()
    mat"""
    subplot(3,1,1);
    title('X, Y, Z Coordinates Over Time', 'FontSize', 20)
    hold on;
    grid on;
    plot($thist, $xonly, 'DisplayName','IPOPT Results', 'LineWidth', 2)
    plot($thist, $xRef, 'DisplayName','Reference', 'LineWidth', 2)
    ax = gca;
    ax.FontSize = 14;
    xlim([0 $Tfinal])
    xlabel('T Period', 'FontSize', 16)
    ylabel('X', 'FontSize', 16)
    legend('FontSize', 16)
    hold off;

    subplot(3,1,2);
    hold on;
    grid on;
    plot($thist, $yonly, 'LineWidth', 2)
    plot($thist, $yRef, 'LineWidth', 2)
    ax = gca;
    ax.FontSize = 14;
    xlim([0 $Tfinal])
    xlabel('T Period', 'FontSize', 16)
    ylabel('Y', 'FontSize', 16)
    hold off;

    subplot(3,1,3);
    hold on;
    grid on;
    plot($thist, $zonly, 'LineWidth', 2)
    plot($thist, $zRef, 'LineWidth', 2)
    ax = gca;
    ax.FontSize = 14;
    xlim([0 $Tfinal])
    xlabel('T Period', 'FontSize', 16)
    ylabel('Z', 'FontSize', 16)
    hold off;
    """
end

# Plot IPOPT orbits' timesteps
function IPOPT_Timesteps_Plot()
    mat"""
    title('IPOPT Timesteps', 'FontSize', 20)
    hold on
    grid on
    scatter($thist, $uonly, 50, 'MarkerEdgeColor', 'k',...
                                'MarkerFaceColor', [0 .7 .7],...
                                'LineWidth',1.5)
    xlabel('Timesteps', 'FontSize', 16)
    ylabel('h', 'FontSize', 16)
    xlim([0 $Tfinal])
    hold off
    ax = gca;
    ax.FontSize = 14;
    """
end

# Plot family of orbits generated by IPOPT
function Family_Orbits_Plot()
    mat"""
    plot3($xRef,$yRef,$zRef,'k-','DisplayName','Reference')
    hold on
    grid on
    plot3($x_fam(1,:,1),$x_fam(2,:,1),$x_fam(3,:,1),'r-','DisplayName','IPOPT Results')
    for i = 2:$L
        plot3($x_fam(1,:,i),$x_fam(2,:,i),$x_fam(3,:,i),'r-')
    end
    hold off
    title('Family of Orbits around L1 (200 iterations, scaling by 5%)', 'FontSize', 20)
    xlabel('X', 'FontSize', 20)
    ylabel('Y', 'FontSize', 20)
    zlabel('Z', 'FontSize', 20)
    view(25, 15)
    legend('Reference','IPOPT Results', 'FontSize', 16)
    ax = gca;
    ax.FontSize = 14;
    """
end

# TVLQR Plotting
function TVQLR_Plot()
    mat"""
    hold on
    grid on
    plot3($xtrajX, $xtrajY, $xtrajZ, 'k--', 'LineWidth', 1,  'DisplayName','Reference')
    plot3($XsatX, $XsatY, $XsatZ, 'r', 'LineWidth', 3,  'DisplayName','TVLQR')
    hold off
    view(25, 15)
    ax = gca;
    ax.FontSize = 14;
    title('TVLQR vs. Reference', 'FontSize', 20)
    xlabel('X', 'FontSize', 16)
    ylabel('Y', 'FontSize', 16)
    zlabel('Z', 'FontSize', 16)
    legend('FontSize', 16)
    """
    return nothing
end
